### ISSUE TITLE
Missing Python PIP Packages when running createindex.py

### ISSUE THREAD

**Issue by Factorization** [Kwaai-AI-Lab/PAIAssistant#4]
I ran into an issue when running the `createindex.py` script. It looks like the python package `langchain_community` is missing:
<img width="502" alt="image" src="https://github.com/user-attachments/assets/fa24b9d5-4257-48ce-9110-8d92581534c2">

According to the `langchain` documentation, the `langchain_community` package should be installed when the `langchain` package is installed, but it looks like that is not happening:
![image](https://github.com/user-attachments/assets/b10d91e5-b23a-4310-a66e-c641ff4b5af9)

It is probably best to include `langchain_community` in the `requirements.txt` file to make sure it is installed.

I ran into a similar issue last week when I was running the `createindex.py` script, but it was missing a different pip package, the `llama-index-llms-fireworks` package. It might be best to use something like `pip-compile` from [pip-tools](https://pypi.org/project/pip-tools/) to pin all the required python packages and transitive dependencies. This will provide a more predictable and deterministic build.

**Comment by balajilx** [comment]
@Factorization Thanks for bringing this to attention. Will fix this by end of week!

**Comment by balajilx** [comment]
langchain-community explicitly added to requirements.txt
